### ISSUE TITLE
Status Light For Atom M5?

### ISSUE THREAD

**Issue by mediamanrit** [Ylianst/ESP-IQ2020#20]
I've been trying to make this work and just can't.  My ESPHome skills aren't up to par yet.  Is there a way to be able to light the RGB LED when the Atom boots, and leave it lit?

Why?  Because it seems like my Atom is just not working, BUT, I can write software to it.  It's not coming up on my home WiFi, but it also isn't advertising its own AP/Captive Portal either.  So, having an "I'm booted" status light would just prove it's at least on.

Better would be a thing like:

- Blue: Booted (Step 1)
- Green: Connected to WiFi (Step 2)

**Comment by Ylianst** [comment]
Is it this device you have?

![image](https://github.com/user-attachments/assets/37ac3b72-c46f-45d5-b96a-ec00fcfaafa9)

If so, add this:

```
light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: 27
    num_leds: 1
    rgb_order: GRB
    id: status_led
    name: M5Atom Light
    effects:
      - random:
      - flicker:
      - addressable_rainbow:

binary_sensor:
    platform: gpio
    pin:
      number: 39
      inverted: true
    name: M5Atom Button
    on_press:
      then:
        - light.toggle: status_led
        - homeassistant.event:
            event: esphome.button_pressed
            data:
              button: M5Atom Button
    on_press:
      then:
      - light.toggle: status_led
```

This should make it so the LED will do something when you press the button and so, signal that something is alive.

Also, the ATOM has only 2.4Ghz WIFI, so, if your router is 5Ghz, it will not connect.
