### ISSUE TITLE
Energy consumption for energy dashboard

### ISSUE THREAD

**Issue by milesroper** [Ylianst/ESP-IQ2020#34]
Hi,
Trying to get power use showing in energy dashboard for the water heater sensor.  I think there is a  device_class: Energy setting missing.

https://community.home-assistant.io/t/integration-riemann-sum-integral-for-solar-panels-showing-unexpected-device-class/551996/15

Has a bunch of info, basically the riemann sensor is coming up with an error in the energy dashboard, which i think the root cause is the entity doesnt have the device class included.  Ive tried adding the device class into the esphone yaml config/and recompiled onto the esphome device.  I've checked the states in developer tools and the device class doesnt show up.  I figure somewhere in your code it defines those values.  Hopefully this makes sense if you can point me in the write direction would be appreciated.

Regards
Miles

**Comment by milesroper** [comment]
Found some instructions for energy use in the other general discussion which i think will work.

**Comment by milesroper** [comment]
Immm, says the new entity is unavailable, will leave it overnight and see if it self resolves.

**Comment by Ylianst** [comment]
@milesroper - Give this a try, this is was I use. Add these sensors if you don't have then already. Let me know how it goes.

```
sensor:
  - platform: iq2020
    power_l1:
      internal: true
      name: Pump Power
      id: power_l1
    power_heater:
      internal: true
      name: Controller Power
      id: power_heater
    power_l2:
      internal: true
      name: Heater Power
      id: power_l2
  - platform: total_daily_energy
    name: 'Pump Energy'
    power_id: power_l1
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
  - platform: total_daily_energy
    name: 'Controller Energy'
    power_id: power_heater
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
  - platform: total_daily_energy
    name: 'Heater Energy'
    power_id: power_l2
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
```
