### ISSUE TITLE
Display current date and time on the hot tub remote

### ISSUE THREAD

**Issue by Ylianst** [Ylianst/ESP-IQ2020#44]
If you are using the [audio module emulation mode](https://github.com/Ylianst/ESP-IQ2020/blob/main/documentation/audio.md), you can display a song title and song name on the remote. Well, I finally decided to make use of this and have Home Assistant display the current time and date in these fields. For the date, I just have an automation that once a day sets the current date in the format I want. You can ask ChatGPT for any format you like.

```
alias: Hot Tub Date
description: ""
triggers:
  - trigger: time_pattern
    hours: "0"
conditions: []
actions:
  - action: text.set_value
    metadata: {}
    data:
      value: "{{ now().strftime('%A, %B %-d, %Y') }}"
    target:
      entity_id: text.hot_tub_artist_name
mode: single
```

For the time, I did not want to send a new time string every minutes all day even when the hot tub is not used, so, I only do it when the hot tub lights are on.

```
alias: Hot Tub Time
description: ""
triggers:
  - trigger: time_pattern
    minutes: "*"
conditions:
  - condition: device
    type: is_on
    device_id: d2185a53e2d8a77972250c1e1d95cb3d
    entity_id: 5caa74c388e8df5402ddcc433c9439c9
    domain: switch
    enabled: true
actions:
  - action: text.set_value
    metadata: {}
    data:
      value: "{{ now().strftime('%I:%M %p') }}"
    target:
      entity_id: text.hot_tub_song_title
mode: single
```

You can see the results in Home Assistant:

![Image](https://github.com/user-attachments/assets/85d765fd-981b-4275-a05e-b8debeba95ac)

Of course, you only see the song title and artist names when your input is set to Bluetooth, but you can change that in Home Assistant or on the remote. In any case, it's a fun little quality of life improvement. We can now check the time on the remote.

One thing that is odd is that the IQ2020 does have an internal clock and the DataViewer tool can set it to the correct time, however, they never used that on the remote.
