### ISSUE TITLE
Pumps power and heater power reading 0 W

### ISSUE THREAD

**Issue by rossbrouse** [Ylianst/ESP-IQ2020#8]
I've noticed that it's not pulling any data for pumps power or heater power. Is that expected>
Here is that section from my config:

    power_on_counter:
      name: Power On Counter
    power_l1:
      name: Pumps Power
#    power_heater:
#      name: Power Heater
    power_l2:
      name: Heater Power

**Comment by Ylianst** [comment]
Hi. These values are polled along with the other values in one go, I don't get to pick not to poll them. This said, various versions of the IQ2020 seem to offer different values. What model hot tub do you have?

**Comment by rossbrouse** [comment]
It's a 2024 Hotspring relay and uses the IQ2020 Watkins 1303401-1 controller.

**Comment by Ylianst** [comment]
Ok, add the following sensors and let me know what you see when the heaters and pumps are on:

```
sensor:
  - platform: iq2020-dev
    voltage_l1:
      name: Voltage L1
    voltage_heater:
      name: Voltage Heater
    voltage_l2:
      name: Voltage L2
    current_l1:
      name: Current L1
    current_heater:
      name: Current Heater
    current_l2:
      name: Current L2
```

You should see the added sensors here:

![image](https://github.com/Ylianst/ESP-IQ2020/assets/1319013/94978fd6-ed99-473f-a2e9-092c2a3c4281)

**Comment by rossbrouse** [comment]
I can't recompile and install using the iq2020-dev platform. Is using the iq2020-dev platform required?

In file included from src/esphome.h:33,
                 from src/main.cpp:3:
src/esphome/components/iq2020-dev/iq2020.h:52:7: error: redefinition of 'class IQ2020Component'
 class IQ2020Component : public esphome::Component {
       ^~~~~~~~~~~~~~~
In file included from src/esphome.h:26,
                 from src/main.cpp:3:
src/esphome/components/iq2020/iq2020.h:52:7: note: previous definition of 'class IQ2020Component'
 class IQ2020Component : public esphome::Component {

**Comment by rossbrouse** [comment]
Look like Current L2 went up to 15 amps when Jets 1 turned on as a result of the heater turning on. Current L1 still registers only 0 watts.

**Comment by Ylianst** [comment]
Apologies. Yes, always use `iq2020` and not `iq2020-dev`, that is my own development version so I can test things without breaking the "production" version. You did the right thing. It does not look like you have a power meter. If you really want to investigate this further, add the following line to your config:

```
# Relay UART messages over TCP
iq2020:
   uart_id: SpaConnection
   port: 1234                               <---------- Add this line
```

Re-flash the ESP32 device then download the [Windows Data Viewer app](https://github.com/Ylianst/ESP-IQ2020/raw/main/DataViewer/IQ2020-DataViewer.exe) and connect it to the ESP32 using the IP address and port 1234. You will start seeing traffic like this:

![image](https://github.com/Ylianst/ESP-IQ2020/assets/1319013/fc9282bb-9837-4ea5-b3a6-24df48ccd20a)

You can then go in the "file" menu and select "log to file..." and start a capture. In "Actions" select "Ask Status (x0256)" and send the results back here. Basically, that will give us a complete status of your device and I will be able to decode all the values. You can also go in the "state" panel and see the entire decoded state:

![image](https://github.com/Ylianst/ESP-IQ2020/assets/1319013/b116f872-d992-4209-89dd-e0680cd4915c)
